# From the Youtbue video Github Actions and Octopus Deploy

name: test2 Build and create release

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

env:
  Solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

jobs:
  lukesBuild:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ${{ github.workspace }}\nub_tst_lukeapi.csproj --configuration {{ env.buildConfiguration }} --output ${{ github.workspace }}\output\nub_tst_lukeapi\

