# From the Youtbue video Github Actions and Octopus Deploy

name: test2 Build and create release

on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]
  workflow_dispatch:

env:
  Solution: '**/*.sln'
  buildPlatform: Any CPU
  buildConfiguration: Release

jobs:
  lukesBuild:
    runs-on: self-hosted  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    steps:
    - uses: actions/checkout@v4

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish
      run: dotnet publish ${{ github.workspace }}\nub_tst_lukeapi.csproj --configuration ${{ env.buildConfiguration }} --output ${{ github.workspace }}\output\nub_tst_lukeapi\
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.6
      id: upload-artifact
      with:
        name: Luke test api artifact
        path: ${{ github.workspace }}\output\nub_tst_lukeapi\
        retention-days: 1

  lukesDeploy:
    runs-on: self-hosted
    needs: lukesBuild
    environment: dev

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: Luke test api artifact
        path: .\theartifact
        
